alias: Turn on storage light when there is movement
trigger:
  platform: state
  entity_id: binary_sensor.motion_berging_sensor_78_0
  to: 'on'
condition:
  condition: state
  entity_id: switch.lamp_berging_switch_44_0
  state: 'off'
action:
  service: homeassistant.turn_on
  entity_id: switch.lamp_berging_switch_44_0
