alias: Turn off storage light 2 minutes after last movement
trigger:
  platform: state
  entity_id: binary_sensor.motion_berging_sensor_78_0
  to: 'off'
  for:
    minutes: 2
action:
  service: homeassistant.turn_off
  entity_id: switch.lamp_berging_switch_44_0
