alias: Turn off 1e floor hallway light 2 minutes after last movement
trigger:
  platform: state
  entity_id: binary_sensor.motion_gang_1e_sensor
  to: 'off'
  for:
    minutes: 2
action:
  service: homeassistant.turn_off
  entity_id: switch.lamp_bg1e_switch_2
