alias: Turn on hallway light ground floor when there is movement
trigger:
  platform: state
  entity_id: binary_sensor.motion_gang_begane_grond_sensor_76_0
  to: 'on'
condition:
  condition: state
  entity_id: switch.lamp_bg1e_switch_50_0
  state: 'off'
action:
  service: homeassistant.turn_on
  entity_id: switch.lamp_bg1e_switch_50_0
