alias: Turn off ground floor hallway light 2 minutes after last movement
trigger:
  platform: state
  entity_id: binary_sensor.motion_gang_begane_grond_sensor
  to: 'off'
  for:
    minutes: 2
action:
  service: homeassistant.turn_off
  entity_id: switch.lamp_bg1e_switch
