- alias: Turn on hallway light ground floor when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_gang_begane_grond_sensor
    to: 'on'
  condition:
    condition: state
    entity_id: switch.lamp_bg1e_switch
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.lamp_bg1e_switch

- alias: Turn off ground floor hallway light 2 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_gang_begane_grond_sensor
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: switch.lamp_bg1e_switch
