alias: Turn on kitchen floor led lightning to Blue
trigger:
  platform: state
  entity_id: binary_sensor.motion_keuken_sensor
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.keuken_rgb_vloerrand_level
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: below_horizon
action:
  service: homeassistant.turn_on
  data:
    entity_id: light.keuken_rgb_vloerrand_level
    rgb_color: [10,2,239]
    brightness: 255
