language: python
addons:
    apt:
        packages:
            #see https://www.home-assistant.io/components/stream/#troubleshooting
            - autoconf
            - libssl-dev
            - libxml2-dev
            - libxslt1-dev
            - libjpeg-dev
            - libffi-dev
            - libudev-dev
            - zlib1g-dev
            - python-dev
            - pkg-config
            - libavformat-dev
            - libavcodec-dev
            - libavdevice-dev
            - libavutil-dev
            - libswscale-dev
            - libavresample-dev
            - libavfilter-dev
            
python:
  - "3.6.4"
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install -U setuptools
  - pip3 install homeassistant
  - pip3 install colorlog
script:
  - hass -c . --script check_config --info all