language: python
python:
  - "3.6"
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - apt-get install -y python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
  - pip3 install homeassistant
  - pip3 install colorlog
script:
  - hass -c . --script check_config --info all