- action:
  - alias: ''
    data:
      message: New version out
      title: New version out
    service: notify.ios_ierik
  alias: New Version out
  id: '1495725269132'
  trigger:
    platform: state
    entity_id: updater.updater
- action:
  - alias: ''
    data:
      message: Z-wave done
      title: Home Assistant
    service: notify.ios_ierik
  alias: Zwave network ready
  id: '1495725269133'
  trigger:
    platform: event
    event_type: zwave.network_ready
- action:
  - alias: Say text on coming home vio
    data:
      sonos_entity: media_player.keuken
      volume: 0.5
      delay: 00:00:09
    data_template:
      message: Violet komt eraan, ze is nog {{states('sensor.vio_to_home')}} minuten
        verwijderd.
    service: script.sonos_say
  alias: Warn when girlfriend comes home
  condition:
  - condition: state
    entity_id: device_tracker.ierik
    state: home
  id: '1505155570053'
  trigger:
  - entity_id: device_tracker.ivio
    event: leave
    platform: zone
    zone: zone.horses
  - entity_id: device_tracker.ivio
    event: leave
    platform: zone
    zone: zone.work_vio
- action:
  - alias: Turn on lights koepel
    data:
      entity_id: switch.led_oprit_switch
    service: homeassistant.turn_on
  alias: Frontdoor motion lights on
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  id: '1505645427801'
  trigger:
  - platform: event
    event_type: doorbird_voordeur_motion
- action:
  - alias: Turn off led koepel after xx minutes
    data:
      entity_id: switch.led_oprit_switch
    service: homeassistant.turn_off
  id: '1505645427802'
  trigger:
  - entity_id: switch.led_oprit_switch
    for:
      minutes: 3
    platform: state
    to: 'on'
  alias: Turn off led koepel after xx minutes
- action:
  - alias: Start HomeKit
    service: homekit.start
  alias: Start HomeKit
  trigger:
  - platform: event
    event_type: zwave.network_ready
  id: 273ddac32b4a4e48a9737a3679523768
- id: '1550705836735'
  alias: Open frontdoor with doorbird
  trigger:
  - event_data: {}
    event_type: doorbird_voordeur_relay
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.entree_deur_opener_switch
    service: homeassistant.turn_on
