homeassistant:
  packages: !include_dir_named extraconfig/packages
  customize: !include customize.yaml
  customize_glob: !include_dir_merge_named extraconfig/standalonefiles/customize_glob.yaml

frontend:
  themes: !include_dir_merge_named themes

fibaro:
  gateways:
    - url: http://192.168.1.92/api/
      username: !secret default_email
      password: !secret fibaro_password

config:
http:

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# The sun
sun:

# Create presence person groups
person:

# Allow for streams
stream: 

discovery:
  ignore:
    - homekit

# mqtt:
#   discovery: true
#   discovery_prefix: hass
#   broker: 192.168.1.81
#   birth_message:
#     topic: 'hass/status'
#     payload: 'online'
#   will_message:
#     topic: 'hass/status'
#     payload: 'offline'

ios:
mobile_app:
map:
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
  # run_test: true

hacs:
  token: !secret my_github_access_token

# folders with the component name of pre subfolder
sensor: !include_dir_merge_list extraconfig/sensors
binary_sensor: !include_dir_merge_list extraconfig/binary_sensors

# Normal include
google: !include extraconfig/standalonefiles/googlecalendar.yaml
tesla: !include extraconfig/standalonefiles/tesla.yaml
camera: !include extraconfig/standalonefiles/camera.yaml
# hdmi_cec: !include extraconfig/standalonefiles/hdmi_cec.yaml # if this is ever stable..
logger: !include extraconfig/standalonefiles/logger.yaml
recorder: !include extraconfig/standalonefiles/recorder.yaml
tts: !include extraconfig/standalonefiles/tts.yaml
weather: !include extraconfig/standalonefiles/weather.yaml
withings: !include extraconfig/standalonefiles/withings.yaml
cloud: !include extraconfig/standalonefiles/cloud.yaml
device_tracker: !include extraconfig/standalonefiles/device_tracker.yaml
history: !include extraconfig/standalonefiles/history.yaml
logbook: !include extraconfig/standalonefiles/logbook.yaml

# Dir list
automation old: !include_dir_merge_list extraconfig/automation
automation: !include automations.yaml

system_health:

# emulated_hue:
#   listen_port: 80
#   expose_by_default: true
#   exposed_domains:
#   - light