homeassistant:
  packages: !include_dir_named extraconfig/packages
  customize: !include customize.yaml
  customize_glob: !include_dir_merge_named extraconfig/standalonefiles/customize_glob.yaml

frontend:
  themes: !include extraconfig/standalonefiles/themes.yaml

config:
http:
  base_url: !secret base_url

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# The sun
sun:

# Create presence person groups
person:

# Allow for streams
stream: 

discovery:
  ignore:
    - homekit

mqtt:
  broker: a0d7b954-mqtt
  password: !secret mqtt_pass 
  username: !secret mqtt_user
  client_id: home-assistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

ios:
mobile_app:
map:
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
  # run_test: true

hacs:
  token: !secret my_github_access_token

breaking_changes:

# folders with the component name of pre subfolder
sensor: !include_dir_merge_list extraconfig/sensors
binary_sensor: !include_dir_merge_list extraconfig/binary_sensors

# Normal include
media_player: !include extraconfig/standalonefiles/media_player.yaml
zone: !include extraconfig/standalonefiles/zones.yaml
google: !include extraconfig/standalonefiles/googlecalendar.yaml
tesla: !include extraconfig/standalonefiles/tesla.yaml
camera: !include extraconfig/standalonefiles/camera.yaml
# hdmi_cec: !include extraconfig/standalonefiles/hdmi_cec.yaml # if this is ever stable..
vacuum: !include extraconfig/standalonefiles/vacuum.yaml
logger: !include extraconfig/standalonefiles/logger.yaml
recorder: !include extraconfig/standalonefiles/recorder.yaml
tts: !include extraconfig/standalonefiles/tts.yaml
weather: !include extraconfig/standalonefiles/weather.yaml
withings: !include extraconfig/standalonefiles/withings.yaml
# climate: !include extraconfig/standalonefiles/climate.yaml # Once i get plugwise better
cloud: !include extraconfig/standalonefiles/cloud.yaml
influxdb: !include extraconfig/standalonefiles/influxdb.yaml
device_tracker: !include extraconfig/standalonefiles/device_tracker.yaml
history: !include extraconfig/standalonefiles/history.yaml
logbook: !include extraconfig/standalonefiles/logbook.yaml

# Dir list
automation: !include_dir_merge_list extraconfig/automation

system_health:

# panels
panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: !secret grafana_url
  zwave2mqtt:
    title: Zwave2Mqtt
    icon: mdi:access-point-network
    url: !secret zwave2mqtt_url

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave


