homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
#  customize: !include_dir_merge_named extraconfig/customize
  customize: !include customize.yaml
  packages: !include_dir_named extraconfig/packages
  customize_glob: !include_dir_merge_named extraconfig/customize_glob

frontend:
#  javascript_version: latest
config:
http:
  # api_password: !secret api_password
  base_url: !secret base_url
  trusted_networks:
    - 192.168.1.115

# Checks for available updates
updater:

# Cloud options
cloud:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# History stuff
history:
logbook:
sun:

# Create presence person groups
person:

# Allow for streams
stream: 

#discovery:

zwave:
 usb_path: /dev/ttyACM1
 autoheal: false
 polling_interval: 0
 network_key: !secret network_key
 debug: false

homekit:
  auto_start: False
  filter:
    include_domains:
      - light
      - climate

ios:
mobile_app:
map:
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
  # run_test: true


# folders with the component name of pre subfolder
sensor: !include_dir_merge_list extraconfig/sensors
binary_sensor: !include_dir_merge_list extraconfig/binary_sensors

# folders that don't need to include the first item via include_dir_merge_named
group: !include_dir_merge_named extraconfig/groups
#shell_command: !include_dir_merge_named extraconfig/shell_command
script: !include_dir_merge_named extraconfig/scripts

# Normal include
media_player: !include extraconfig/standalonefiles/media_player.yaml
zone: !include extraconfig/standalonefiles/zones.yaml
google: !include extraconfig/standalonefiles/googlecalendar.yaml
netatmo: !include extraconfig/standalonefiles/netatmo.yaml
tesla: !include extraconfig/standalonefiles/tesla.yaml
camera: !include extraconfig/standalonefiles/camera.yaml
# hdmi_cec: !include extraconfig/standalonefiles/hdmi_cec.yaml
vacuum: !include extraconfig/standalonefiles/vacuum.yaml
logger: !include extraconfig/standalonefiles/logger.yaml
recorder: !include extraconfig/standalonefiles/recorder.yaml
tts: !include extraconfig/standalonefiles/tts.yaml
weather: !include extraconfig/standalonefiles/weather.yaml
# climate: !include extraconfig/standalonefiles/climate.yaml # once plugwise if further
google_assistant: !include extraconfig/standalonefiles/googleassistant.yaml
influxdb: !include extraconfig/standalonefiles/influxdb.yaml
# image_processing: !include extraconfig/standalonefiles/image_processing.yaml # disabled for now.. cpu heavy. Needs to be more friendly.
device_tracker: !include extraconfig/standalonefiles/device_tracker.yaml

# Dir list
automation old: !include_dir_list extraconfig/automation

automation: !include automations.yaml
system_health:

# panels
panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: !secret grafana_url

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave