# ################################################################
# ## Package / Doorbird options
# ################################################################

doorbird:
  devices:
    - host: !secret doorbird_ip
      username: !secret doorbird_username
      password: !secret doorbird_password
      hass_url_override: http://192.168.1.81:8123
      token: !secret doorbird_token
      name: Voordeur
      events:
        - motion
        - open_door

camera:
  - platform: doorbird

automation:
  - alias: Open frontdoor with doorbird
    trigger:
      event_type: doorbird_voordeur_open_door
      platform: event
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.entree_deur_opener_switch
