# ################################################################
# ## Package / Doorbird options
# ################################################################

doorbird:
  devices:
    - host: !secret doorbird_ip
      username: !secret doorbird_username
      password: !secret doorbird_password
      hass_url_override: http://192.168.1.81:8123
      token: !secret doorbird_token
      name: Voordeur
      events:
        - motion
        - open_door
        - doorbell

camera:
  - platform: doorbird

automation:
  - alias: Open frontdoor with doorbird
    trigger:
      event_type: doorbird_voordeur_open_door
      platform: event
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.entree_deur_opener_switch

  - alias: Someone at the door
    trigger:
      event_type: doorbird_voordeur_doorbell
      platform: event
    condition:
    - condition: state
      entity_id: device_tracker.ierik
      state: 'home'
    - condition: state
      entity_id: device_tracker.ivio
      state: home
    action:
      service: script.sonos_say
      data:
        sonos_entity: media_player.keuken
        volume: 0.7
        delay: 00:00:09
      data_template:
        message: Er staat iemand voor de deur. Wie gaat er rennen?