# this select is set by the bed set and bed clear automations
# in the event the sensor breaks this can be set manually

# Erik
input_select:
  in_bed_erik:
    initial: Occupied
    name: Erik in bed
    options:
      - Occupied
      - Not Occupied
      - Frisky Hands
    icon: mdi:hotel
  in_bed_vio:
    initial: Occupied
    name: Vio in bed
    options:
      - Occupied
      - Not Occupied
      - Frisky Hands
    icon: mdi:hotel

# sensor for the mass published by the device
# Erik
sensor:
  - platform: mqtt
    state_topic: "homeassistant/sensor/masterbed_erik/load"
    name: Bed Massa Erik
    unit_of_measurement: "kg"
    icon: mdi:weight-kilogram
  - platform: mqtt
    state_topic: "homeassistant/sensor/masterbed_vio/load"
    name: Bed Massa Vio
    unit_of_measurement: "kg"
    icon: mdi:weight-kilogram

# zeros out the current reading
script:
  zero_bed:
    alias: Tare Beds
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/sensor/masterbed_erik/tare"
          payload: '0'
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/sensor/masterbed_vio/tare"
          payload: '0'

# Automations
automation:
  - alias: Set bed when erik is in it
    hide_entity: True
    trigger:
      platform: state
      entity_id: sensor.bed_massa_erik
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bed_massa_erik
          above: '50'
        - condition: numeric_state
          entity_id: sensor.bed_massa_erik
          below: '110'
        - condition: state
          entity_id: device_tracker.ierik
          state: 'home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.in_bed_erik
          option: 'Occupied'
  - alias: Set bed when vio is in it
    hide_entity: True
    trigger:
      platform: state
      entity_id: sensor.bed_massa_vio
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bed_massa_vio
          above: '50'
        - condition: numeric_state
          entity_id: sensor.bed_massa_vio
          below: '110'
        - condition: state
          entity_id: device_tracker.ivio
          state: 'home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.in_bed_vio
          option: 'Occupied'
  - alias: Clear bed when erik is not in it
    hide_entity: True
    trigger:
      platform: state
      entity_id: sensor.bed_massa_erik
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bed_massa_erik
          below: '45'
        - condition: state
          entity_id: device_tracker.ierik
          state: 'home'
        - condition: state
          entity_id: input_select.in_bed_erik
          state: 'Occupied'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.in_bed_erik
          option: 'Not Occupied'
  - alias: Clear bed when vio is not in it
    hide_entity: True
    trigger:
      platform: state
      entity_id: sensor.bed_massa_vio
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bed_massa_vio
          below: '45'
        - condition: state
          entity_id: device_tracker.ivio
          state: 'home'
        - condition: state
          entity_id: input_select.in_bed_vio
          state: 'Occupied'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.in_bed_vio
          option: 'Not Occupied'
  - alias: when 2 people are in eriks bed
    hide_entity: True
    trigger:
      platform: state
      entity_id: sensor.bed_massa_erik
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bed_massa_erik
          above: '120'
        - condition: state
          entity_id: device_tracker.ierik
          state: 'home'
        - condition: state
          entity_id: device_tracker.ivio
          state: 'home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.in_bed_erik
          option: 'Frisky Hands'
  - alias: When 2 people are on vio her bed
    hide_entity: True
    trigger:
      platform: state
      entity_id: sensor.bed_massa_vio
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bed_massa_vio
          above: '120'
        - condition: state
          entity_id: device_tracker.ierik
          state: 'home'
        - condition: state
          entity_id: device_tracker.ivio
          state: 'home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.in_bed_vio
          option: 'Frisky Hands'

  - alias: Bed Occupied task for erik
    trigger:
      platform: state
      entity_id: input_select.in_bed_erik
      to: 'Occupied'
      for:
        seconds: 10
    condition:
      condition: time
      after: '10:00:00'
      before: '04:00:00'
    action:
      - service: light.turn_off
        entity_id: light.lamp_slaapkamer_dimmer_level
      - service: homeassistant.turn_off
        entity_id: 
          - switch.lamp_badkamer_switch
          - switch.lamp_badkamer_switch_2

  - alias: Bed Occupied task for vio
    trigger:
      platform: state
      entity_id: input_select.in_bed_vio
      to: 'Occupied'
    condition:
      condition: time
      after: '20:00:00'
      before: '04:00:00'
    action:
      service: homeassistant.turn_off
      entity_id:
        - switch.lamp_badkamer_switch
        - switch.lamp_badkamer_switch_2

