homeassistant:
  customize:
    script.sonos_say:
      friendly_name: Speech for sonos

notify:
  - name: notify_family
    platform: group
    services:
      - service: ios_ierik
      - service: ios_ivio
  - name: notify_erik
    platform: group
    services:
      - service: ios_ierik
  - name: notify_vio
    platform: group
    services:
      - service: ios_ivio

script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
      - service: sonos.snapshot
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: sonos.unjoin
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.volume_set
        data_template:
          entity_id: "{{ sonos_entity }}"
          volume_level: "{{ volume }}"
      - service: tts.google_translate_say
        data_template:
          entity_id: "{{ sonos_entity }}"
          message: "{{ message }}"
      - delay: "{{ delay }}"
      - service: sonos.restore
        data_template:
          entity_id: "{{ sonos_entity }}"