# ################################################################
# ## Package / Washing machine alert when done
# ################################################################

# sensor:
#   - platform: statistics
#     entity_id: sensor.wasautomaat_power
#     max_age:
#       minutes: 30
#   - platform: template
#     sensors:
#       wasmachine_status:
#         friendly_name: Wasmachine Status
#         value_template: >-
#           {% set power_level = states('sensor.wasautomaat_power')|int('unknown') %}
#           {% if power_level >= 80 %}
#             on
#           {% elif power_level <= 1.2 %}
#             off
#           {% else %}
#             idle
#           {% endif %}
#         icon_template: '{% if is_state("sensor.wasautomaat_status", "on") %}mdi:power{% else %}mdi:sleep{% endif %}'

input_select:
  state_washingmachine:
    initial: Powered Down
    name: Washing Machine state
    options:
      - Powered Down
      - Idle
      - Rinse / Spin
      - Wash
    icon: mdi:tumble-dryer

automation:
  - id: washingmachine_powereddown
    alias: 'Washing Machine - Change State Powered Down'
    trigger:
      - platform: state
        entity_id: switch.wasautomaat_switch
        to: 'on'
      - platform: numeric_state
        entity_id: sensor.wasautomaat_power
        below: 4
        for: '00:01:00'
    condition:
    - condition: state
      entity_id: switch.wasautomaat_switch
      state: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.state_washingmachine
          option: 'Powered Down'

  - id: washingmachine_idle
    alias: 'Washing Machine - Change State Idle'
    trigger:
      - platform: numeric_state
        entity_id: sensor.wasautomaat_power
        above: 4
        below: 25
        for: '00:01:00'
    condition:
      - condition: state
        entity_id: switch.wasautomaat_switch
        state: 'on'
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.state_washingmachine
          state: 'Powered Down'
        - condition: state
          entity_id: input_select.state_washingmachine
          state: 'Rinse / Spin'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.state_washingmachine
          option: 'Idle'

  - id: washingmachine_rinsespin
    alias: 'Washing Machine - Change State Rinse Spin'
    trigger:
      - platform: numeric_state
        entity_id: sensor.wasautomaat_power
        above: 10
        below: 550
        for: '00:01:00'
    condition:
      - condition: state
        entity_id: switch.wasautomaat_switch
        state: 'on'
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.state_washingmachine
          state: 'Powered Down'
        - condition: state
          entity_id: input_select.state_washingmachine
          state: 'Idle'
        - condition: state
          entity_id: input_select.state_washingmachine
          state: 'Wash'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.state_washingmachine
          option: 'Rinse / Spin'

  - id: washingmachine_wash
    alias: 'Washing Machine - Change State Wash'
    trigger:
      - platform: numeric_state
        entity_id: sensor.wasautomaat_power
        above: 600
        for: '00:01:00'
    condition:
      - condition: state
        entity_id: switch.wasautomaat_switch
        state: 'on'
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.state_washingmachine
          state: 'Powered Down'
        - condition: state
          entity_id: input_select.state_washingmachine
          state: 'Idle'
        - condition: state
          entity_id: input_select.state_washingmachine
          state: 'Rinse / Spin'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.state_washingmachine
          option: 'Wash'

  - id: washing_alert
    alias: 'wasmachine alert'
    trigger:
      platform: state
      entity_id: input_select.state_washingmachine
      to: 'Idle'
      for:
        seconds: 120
    condition:
      - condition: state
        entity_id: device_tracker.ierik
        state: 'home'
    action:
      - service: notify.notify_erik
        data_template:
          title: "Wasmachine legen!"
          message:  "Wasmachine ging van draaien naar niets doen, scheitwas ophangen?"
