- alias: Turn on kitchen lights
  trigger:
    platform: state
    entity_id: binary_sensor.keuken_motion_100
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.lamp_keuken_switch
        state: 'off'
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 1.5
      - condition: time
        after: '21:00:00'
        before: '23:59:00'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.lamp_keuken_switch

- alias: Turn off kitchen lights
  trigger:
    platform: state
    entity_id: binary_sensor.keuken_motion_100
    to: 'off'
    for:
      minutes: 10
  action:
  - service: light.turn_off
    entity_id: light.keuken_lamp_vloer_205
  - service: light.turn_off
    entity_id: light.keuken_lamp_45
  - service: light.turn_off
    entity_id: light.keuken_lamp_kastjes_62
  - service: light.turn_off
    entity_id: light.keuken_vide_lamp_49