- alias: Turn off light if sun is up outside patio
  trigger:
    platform: state
    entity_id: light.keuken_lamp_51
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: '4.0'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.keuken_lamp_51
    - service: script.sonos_say
      data:
        sonos_entity: media_player.keuken
        volume: 0.4
        delay: '00:00:03'
        message: "MAND!"