- platform: google_travel_time
  api_key: !secret google_api_distance
  name: Vio naar thuis
  origin: device_tracker.ivio
  destination: zone.home

- platform: google_travel_time
  api_key: !secret google_api_distance
  name: Erik naar thuis
  origin: device_tracker.ierik
  destination: zone.home

- platform: google_travel_time
  api_key: !secret google_api_distance
  name: Thuis naar werk Vio
  origin: device_tracker.ivio
  destination: zone.work_vio

- platform: google_travel_time
  api_key: !secret google_api_distance
  name: Thuis naar werk Erik
  origin: device_tracker.ierik
  destination: zone.work
