- platform: sql
  db_url: !secret db_url
  queries:
    - name: DB size
      query: 'SELECT table_schema "homeassistant", Round(Sum(data_length + index_length) / 1024 /1024 , 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema LIMIT 1;'
      column: 'value'
      unit_of_measurement: MB