- platform: template
  sensors:
    wasmachine_status:
      value_template: "{{ states.input_select.wasmachine_status.state }}"
      friendly_name: 'Wasmachine status'
    wasmachine_klaar:
      value_template: > 
        {%- if (states("sensor.wasmachine_power")| float ) < 40 -%} 
          true
        {%- else -%}
          false
        {%- endif -%}