- platform: waze_travel_time
  origin: zone.home
  destination: zone.werk_ing
  region: 'EU'
  name: Erik home to Work

- platform: waze_travel_time
  origin: person.erik
  destination: zone.home
  region: 'EU'
  name: Erik to Home

- platform: waze_travel_time
  origin: zone.home
  destination: zone.werk_politie
  region: 'EU'
  name: Vio home to Work

- platform: waze_travel_time
  origin: person.vio
  destination: zone.home
  region: 'EU'
  name: Vio to home
  