#- platform: darksky
#  api_key: !secret darsky_api
#  monitored_conditions:
##  lang: nl
#    - ozone

- platform: buienradar
#  latitude: 52.3
#  longitude: 4.75
  timeframe: 30
  name: weather
  monitored_conditions:
    - stationname
    - symbol
    - humidity
    - temperature
    - groundtemperature
    - windspeed
    - windforce
    - winddirection
    - windazimuth
    - pressure
    - visibility
    - windgust
    - precipitation
    - precipitation_forecast_average
    - precipitation_forecast_total
    - irradiance
