- platform: template
  sensors:
    doorbell:
      friendly_name: Doorbell
      device_class: sound
      value_template: 'off'
      entity_id: doorbird.doorbell
    frontdoor_motion:
      friendly_name: Front Door Motion
      device_class: motion
      value_template: 'off'
      entity_id: doorbird.motion
    frontdoor_open:
      friendly_name: Front Door
      device_class: opening
      value_template: 'off'
      entity_id: doorbird.dooropen
