- alias: Turn on driveway lights during end of day
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.oprit_lamp_oprit_140
    - service: homeassistant.turn_on
      data:
        entity_id: light.oprit_lamp_brievenbus_158

- alias: Turn off driveway lights, nobody walks around this time anymore
  trigger:
    platform: time
    at: '01:00:00'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.oprit_lamp_oprit_140
    - service: homeassistant.turn_off
      data:
        entity_id: light.oprit_lamp_brievenbus_158