- alias: Turn on entree light based on an open door event
  trigger:
    platform: state
    entity_id: switch.voordeur_switch
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.lamp_entree_level
        state: 'off'
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 1.5
  action:
    - service: light.turn_on
      entity_id: light.lamp_entree_level

- alias: Turn off entree # but now based on the motion, since motion is detected after the door is open
  trigger:
    platform: state
    entity_id: binary_sensor.motion_entree_sensor
    to: 'off'
    for:
      minutes: 2
  action:
  - service: light.turn_off
    entity_id: light.lamp_entree_level
