- alias: Turn off storage light 2 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.berging_motion_110
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: light.berging_lamp_56

- alias: Turn on storage light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.berging_motion_110
    to: 'on'
  condition:
    condition: state
    entity_id: light.berging_lamp_56
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.berging_lamp_56