- alias: Turn off storage light 2 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_berging_sensor
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: switch.lamp_berging_switch

- alias: Turn on storage light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_berging_sensor
    to: 'on'
  condition:
    condition: state
    entity_id: switch.lamp_berging_switch
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.lamp_berging_switch