- alias: Turn on 1e floor hallway light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.nodeid_100_contact
    to: 'on'
  condition:
    condition: state
    entity_id: switch.nodeid_50_switch_0_2
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.nodeid_50_switch_0_2

- alias: Turn off 1e floor hallway light 2 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.nodeid_100_contact
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: switch.nodeid_50_switch_0_2
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: switch.nodeid_50_switch_0_2