- alias: Turn off any lights 2e floor after 45 minutes
  trigger:
    platform: state
    entity_id: binary_sensor.gang_2e_motion_125
    to: 'off'
    for:
      minutes: 45
  action:
    service: homeassistant.turn_off
    entity_id: 
      - light.gang_2e_lamp_32
      - light.slaapkamer_lamp_77
      - light.badkamer_lamp_87
      - light.badkamer_lamp_spiegel_88
      - light.lexs_lamp_95
      - light.evi_s_lamp_27