- alias: Turn on hallway light ground floor when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.gang_bg_motion_105
    to: 'on'
  condition:
    condition: state
    entity_id: light.gang_bg_lamp_37
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.gang_bg_lamp_37

- alias: Turn off ground floor hallway light 2 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.gang_bg_motion_105
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: light.gang_bg_lamp_37
