- alias: 'Unlock charger when going out of house'
  trigger:
    platform: state
    entity_id: switch.voordeur_switch
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.tesla_model_3_242451_location_tracker
        state: 'home'
      - condition: state
        entity_id: lock.tesla_itesla_charger_door_lock
        state: 'locked'
      - condition: state
        entity_id: binary_sensor.itesla_charger_sensor
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.itesla_battery_sensor
        above: 80
  action:
    service: lock.unlock
    data:
      entity_id: lock.itesla_charger_door_lock