alias: 'Warm Tesla if i just woke up in the morning and it is a workday'
trigger:
  - platform: state
    entity_id: input_select.erik_status_dropdown
    to: 'Just Awake'
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.tesla_model_3_5yj3e7eb5kf242451_battery_sensor
      above: 80
    - condition: numeric_state
      entity_id: sensor.tesla_model_3_5yj3e7eb5kf242451_temperature_sensor_outside
      below: 10
      above: 25
    - condition: state
      entity_id: device_tracker.tesla_model_3_5yj3e7eb5kf242451_location_tracker
      state: 'home'
    - condition: time
      after: '07:00:00'
      before: '10:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
action:
  - service: climate.set_operation_mode
    data:
      entity_id: climate.tesla_model_3_5yj3e7eb5kf242451_hvac_climate_system
      operation_mode: 'on'