- alias: Alert if door is open for longer then 5 minutes
  trigger:
    platform: state
    entity_id: switch.voordeur_switch
    from: 'off'
    to: 'on'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: device_tracker.ierik
    state: 'home'
  action:
    service: notify.notify_erik
    data:
      message: Voordeur staat nog open
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.voordeur