- alias: Alert if door is open for longer then 5 minutes
  trigger:
    platform: state
    entity_id: binary_sensor.unknown_162_1_166
    to: 'on' # better to have from: 'off' aswell, but this device is always on when i reboot HA, go figure.
    for:
      minutes: 5
  action:
    service: notify.notify_erik
    data:
      message: Voordeur staat nog open
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.voordeur