- platform: ffmpeg
  name: Voorkant
  input: !secret camera_voorkant

- platform: ffmpeg
  name: Voordeur
  input: !secret camera_voordeur

- platform: generic
  still_image_url: https://api.buienradar.nl/image/1.0/RadarMapNL?w=256&h=256
  name: Buienradar