- platform: ffmpeg
  name: Keuken
  input: -i rtsp://admin:admin001@192.168.1.58:80/h.264/720p.sdp

- platform: ffmpeg
  name: Lex
  input: -i rtsp://admin:admin001@192.168.1.49:80/h.264/720p.sdp

- platform: ffmpeg
  name: Voorkant
  # host: 192.168.1.50
  input: -rtsp_transport tcp -i rtsp://admin:admin001@192.168.1.80:554/cam/realmonitor?channel=1&subtype=0

# - platform: local_file
#   name: "Tensorflow Voorkant"
#   file_path: /tmp/flow_cam_voorkant.jpg