- platform: ffmpeg
  name: Keuken
  input: !secret camera_keuken

- platform: ffmpeg
  name: Lex
  input: !secret camera_lex

- platform: ffmpeg
  name: Voorkant
  input: !secret camera_voorkant

- platform: ffmpeg
  name: Voordeur
  input: !secret camera_voordeur

# - platform: local_file
#   name: "Tensorflow Voorkant"
#   file_path: /tmp/flow_cam_voorkant.jpg