- platform: mjpeg
  name: Voorkant
  still_image_url: http://192.168.1.135/record/current.jpg
  mjpeg_url: http://192.168.1.135/control/faststream.jpg?stream=full&fps=3
  username: !secret camera_username
  password: !secret camera_password

- platform: mjpeg
  name: Voordeur
  still_image_url: http://192.168.1.136/record/current.jpg
  mjpeg_url: http://192.168.1.136/control/faststream.jpg?stream=full&fps=3
  username: !secret camera_username
  password: !secret camera_password

- platform: generic
  name: Doorbird
  still_image_url: http://192.168.1.115/192.168.1.115/bha-api/image.cgi
  mjpeg_url: http://192.168.1.115/192.168.1.115/bha-api/video.cgi
  username: !secret doorbird_username
  password: !secret doorbird_password
  
- platform: generic
  name: Vio
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.ivio.attributes.latitude }},{{ states.device_tracker.ivio.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.ivio.attributes.latitude }},{{ states.device_tracker.ivio.attributes.longitude }}
  limit_refetch_to_url_change: true
  
- platform: generic
  name: Erik
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.ierik.attributes.latitude }},{{ states.device_tracker.ierik.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.ierik.attributes.latitude }},{{ states.device_tracker.ierik.attributes.longitude }}
  limit_refetch_to_url_change: true