- platform: unifi
  host: 192.168.1.81
  verify_ssl: false
  username: admin
  password: !secret unifi_password
  track_new_devices: no

- platform: tile
  username: !secret default_email
  password: !secret tile_password