- platform: unifi
  host: 192.168.1.81
  verify_ssl: false
  username: admin
  password: !secret unifi_password
  track_new_devices: no
  

- platform: tile
  username: !secret vio_email
  password: !secret tile_password

# - platform: googlehome
#   host: 192.168.1.90
#   rssi_threshold: -100
#   interval_seconds: 5
#   consider_home: 10
#   new_device_defaults:
#     track_new_devices: true