- platform: unifi
  host: 192.168.1.81
  verify_ssl: false
  username: admin
  password: !secret unifi_password
  track_new_devices: no
  

- platform: tile
  username: !secret vio_email
  password: !secret tile_password

- platform: icloud3
  username: !secret default_email
  password: !secret icloud_password
  include_device_type: iphone
  exclude_device: iphonevanjoyce
  unit_of_measurement: km
  waze_region: EU
  sensor_badge_picture:
    - ierik @ /local/erik.png
    - ivio @ /local/vio.png