- alias: Turn on subwoofer is receiver is turned on
  trigger:
    platform: state
    entity_id: media_player.denon_receiver
    to: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.woonkamer_subwoofer_134

- alias: Turn off subwoofer is receiver is turned off
  trigger:
    platform: state
    entity_id: media_player.denon_receiver
    to: 'off'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.woonkamer_subwoofer_134