- alias: Turn on led dome on movement
  trigger:
    platform: event
    event_type: doorbird_voordeur_motion
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    data:
      entity_id: light.oprit_lamp_overkapping_142
    service: homeassistant.turn_on
- alias: Turn off led dome after xx minutes
  trigger:
    entity_id: light.oprit_lamp_overkapping_142
    for:
      minutes: 3
    platform: state
    to: 'on'
  action:
    data:
      entity_id: light.oprit_lamp_overkapping_142
    service: homeassistant.turn_off

